import { LevelConfig } from '../types';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    title: 'Level 1: Paviliun Berhantu',
    titleIndo: 'Lantai 1: Paviliun Berhantu',
    subtitle: 'Menyusup ke rumah tua, curi 3 artefak berharga, dan hindari Inspektur Hantu!',
    theme: 'mansion',
    timeLimitSeconds: 180,
    parTimeSeconds: 65,
    playerStart: { x: -8, z: 8, rotationY: 0 },
    exitDoor: { x: -8, z: 9.8, width: 2.2, height: 3.2, depth: 0.4 },
    rooms: [
      { x: -5, z: 5, width: 10, depth: 10, name: 'Aula Depan (Foyer)', floorTexture: 'checker', wallColor: '#1e1b4b' },
      { x: 5, z: 5, width: 10, depth: 10, name: 'Ruang Tamu & Perapian', floorTexture: 'wood', wallColor: '#312e81' },
      { x: -5, z: -5, width: 10, depth: 10, name: 'Perpustakaan Kuno', floorTexture: 'wood', wallColor: '#3b0764' },
      { x: 5, z: -5, width: 10, depth: 10, name: 'Kamar Koleksi Pribadi', floorTexture: 'carpet_red', wallColor: '#431407' },
    ],
    walls: [
      // Outer boundaries
      { x1: -10, z1: -10, x2: 10, z2: -10, thickness: 0.6, height: 3.5 }, // North
      { x1: -10, z1: 10, x2: 10, z2: 10, thickness: 0.6, height: 3.5 }, // South
      { x1: -10, z1: -10, x2: -10, z2: 10, thickness: 0.6, height: 3.5 }, // West
      { x1: 10, z1: -10, x2: 10, z2: 10, thickness: 0.6, height: 3.5 }, // East

      // Interior dividing walls with open doorways
      // Vertical divider (X=0)
      { x1: 0, z1: 10, x2: 0, z2: 4, thickness: 0.4, height: 3.5 },
      { x1: 0, z1: 1, x2: 0, z2: -1, thickness: 0.4, height: 3.5 },
      { x1: 0, z1: -4, x2: 0, z2: -10, thickness: 0.4, height: 3.5 },

      // Horizontal divider (Z=0)
      { x1: -10, z1: 0, x2: -4, z2: 0, thickness: 0.4, height: 3.5 },
      { x1: -1, z1: 0, x2: 1, z2: 0, thickness: 0.4, height: 3.5 },
      { x1: 4, z1: 0, x2: 10, z2: 0, thickness: 0.4, height: 3.5 },
    ],
    furniture: [
      // Foyer
      { type: 'table', x: -5, y: 0.5, z: 5, width: 2.2, height: 1.0, depth: 1.4, color: '#78350f' },
      { type: 'clock', x: -9.2, y: 1.5, z: 2, width: 0.8, height: 2.8, depth: 0.8, color: '#451a03' },

      // Living Room
      { type: 'sofa', x: 5, y: 0.5, z: 6, width: 3.2, height: 1.1, depth: 1.4, color: '#831843' },
      { type: 'table', x: 5, y: 0.4, z: 4, width: 1.8, height: 0.8, depth: 1.2, color: '#78350f' },

      // Library
      { type: 'bookshelf', x: -9.2, y: 1.6, z: -5, width: 0.8, height: 3.2, depth: 4.5, color: '#451a03' },
      { type: 'desk', x: -5, y: 0.5, z: -5, width: 2.4, height: 1.0, depth: 1.5, color: '#78350f' },

      // Collection Room
      { type: 'cabinet', x: 9.2, y: 1.2, z: -5, width: 0.8, height: 2.4, depth: 3.0, color: '#451a03' },
      { type: 'table', x: 5, y: 0.5, z: -5, width: 2.0, height: 1.0, depth: 2.0, color: '#78350f' },
    ],
    hidingSpots: [
      { id: 'wardrobe_1', type: 'wardrobe', x: -2, y: 0, z: 8.8, rotationY: Math.PI, isOpen: false },
      { id: 'wardrobe_2', type: 'wardrobe', x: 2, y: 0, z: -8.8, rotationY: 0, isOpen: false },
    ],
    loot: [
      // TARGET OBJECTIVES (Must collect to unlock exit)
      {
        id: 'chalice_gold',
        name: 'Cursed Golden Chalice',
        nameIndo: 'Piala Emas Terkutuk',
        value: 1000,
        isObjective: true,
        x: -5,
        y: 1.1,
        z: -5,
        collected: false,
        modelType: 'chalice',
        color: '#facc15',
        sparkleColor: '#fde047',
        description: 'Piala emas berlapis permata milik mendiang raja hantu.',
      },
      {
        id: 'music_box_1',
        name: 'Antique Spirit Music Box',
        nameIndo: 'Kotak Musik Kuno',
        value: 850,
        isObjective: true,
        x: 5,
        y: 0.9,
        z: 4,
        collected: false,
        modelType: 'music_box',
        color: '#ca8a04',
        sparkleColor: '#a855f7',
        description: 'Memutar melodi seram yang disenangi para arwah.',
      },
      {
        id: 'emerald_skull',
        name: 'Emerald Skull Relic',
        nameIndo: 'Tengkorak Zamrud',
        value: 1200,
        isObjective: true,
        x: 5,
        y: 1.1,
        z: -5,
        collected: false,
        modelType: 'skull',
        color: '#10b981',
        sparkleColor: '#34d399',
        description: 'Pahatan tengkorak dari zamrud murni bernilai tinggi.',
      },
      // BONUS LOOT (Extra points & 3-star score)
      {
        id: 'coin_1',
        name: 'Gold Coins Pouch',
        nameIndo: 'Kantong Koin Emas',
        value: 200,
        isObjective: false,
        x: -5,
        y: 1.05,
        z: 5,
        collected: false,
        modelType: 'coin_stack',
        color: '#eab308',
        sparkleColor: '#fef08a',
        description: 'Tumpukan koin emas kuno.',
      },
      {
        id: 'gem_ruby',
        name: 'Blood Ruby Gem',
        nameIndo: 'Permata Rubis Merah',
        value: 400,
        isObjective: false,
        x: 8.5,
        y: 1.3,
        z: -4,
        collected: false,
        modelType: 'gem',
        color: '#ef4444',
        sparkleColor: '#f87171',
        description: 'Permata merah delima berkilau.',
      },
    ],
    ghosts: [
      {
        id: 'ghost_inspector',
        name: 'Inspektur Phantom',
        role: 'polisi',
        x: 5,
        y: 1.3,
        z: 2,
        rotationY: 0,
        speed: 1.9,
        chaseSpeed: 3.6,
        state: 'patrol',
        patrolPoints: [
          { x: 5, z: 6, waitTime: 2.5 },
          { x: 5, z: -6, waitTime: 2.0 },
          { x: -5, z: -2, waitTime: 3.0 },
          { x: -2, z: 4, waitTime: 2.0 },
        ],
        currentWaypointIdx: 0,
        targetInvestigatePos: null,
        stateTimer: 0,
        alertLevel: 0,
        visionAngle: Math.PI / 2.8,
        visionDistance: 7.5,
        hearingDistance: 6.0,
        color: '#38bdf8', // Spooky cyan
      },
    ],
  },

  {
    id: 2,
    title: 'Level 2: Galeri Seni Berhantu',
    titleIndo: 'Lantai 2: Galeri Museum Arwah',
    subtitle: '2 Hantu Penjaga berpatroli! Gunakan mainan pengecoh jika terjebak.',
    theme: 'gallery',
    timeLimitSeconds: 220,
    parTimeSeconds: 85,
    playerStart: { x: -11, z: 0, rotationY: Math.PI / 2 },
    exitDoor: { x: 11.8, z: 0, width: 0.4, height: 3.2, depth: 2.4 },
    rooms: [
      { x: -8, z: 0, width: 8, depth: 16, name: 'Sayap Barat Patung', floorTexture: 'checker', wallColor: '#0f172a' },
      { x: 0, z: 0, width: 8, depth: 16, name: 'Aula Agung Mahkota', floorTexture: 'carpet_red', wallColor: '#1e1b4b' },
      { x: 8, z: 0, width: 8, depth: 16, name: 'Sayap Timur Artefak', floorTexture: 'wood', wallColor: '#312e81' },
    ],
    walls: [
      // Outer perimeter
      { x1: -12, z1: -8, x2: 12, z2: -8, thickness: 0.6, height: 3.8 },
      { x1: -12, z1: 8, x2: 12, z2: 8, thickness: 0.6, height: 3.8 },
      { x1: -12, z1: -8, x2: -12, z2: 8, thickness: 0.6, height: 3.8 },
      { x1: 12, z1: -8, x2: 12, z2: 8, thickness: 0.6, height: 3.8 },

      // Pillar walls dividing the 3 wings
      { x1: -4, z1: -8, x2: -4, z2: -3, thickness: 0.5, height: 3.8 },
      { x1: -4, z1: 3, x2: -4, z2: 8, thickness: 0.5, height: 3.8 },

      { x1: 4, z1: -8, x2: 4, z2: -3, thickness: 0.5, height: 3.8 },
      { x1: 4, z1: 3, x2: 4, z2: 8, thickness: 0.5, height: 3.8 },
    ],
    furniture: [
      // Grand center pedestal
      { type: 'pillar', x: 0, y: 0.6, z: 0, width: 2.2, height: 1.2, depth: 2.2, color: '#f8fafc' },
      { type: 'pillar', x: 0, y: 1.8, z: -5, width: 1.0, height: 3.6, depth: 1.0, color: '#cbd5e1' },
      { type: 'pillar', x: 0, y: 1.8, z: 5, width: 1.0, height: 3.6, depth: 1.0, color: '#cbd5e1' },

      // West wing displays
      { type: 'table', x: -8, y: 0.5, z: -4, width: 2.0, height: 1.0, depth: 1.4, color: '#334155' },
      { type: 'table', x: -8, y: 0.5, z: 4, width: 2.0, height: 1.0, depth: 1.4, color: '#334155' },

      // East wing displays
      { type: 'table', x: 8, y: 0.5, z: -4, width: 2.0, height: 1.0, depth: 1.4, color: '#334155' },
      { type: 'table', x: 8, y: 0.5, z: 4, width: 2.0, height: 1.0, depth: 1.4, color: '#334155' },
    ],
    hidingSpots: [
      { id: 'wardrobe_gallery_1', type: 'wardrobe', x: -10.5, y: 0, z: -6.5, rotationY: 0, isOpen: false },
      { id: 'wardrobe_gallery_2', type: 'wardrobe', x: 0, y: 0, z: 6.8, rotationY: Math.PI, isOpen: false },
      { id: 'wardrobe_gallery_3', type: 'wardrobe', x: 10.5, y: 0, z: -6.5, rotationY: 0, isOpen: false },
    ],
    loot: [
      {
        id: 'queen_crown',
        name: 'Sapphire Spirit Crown',
        nameIndo: 'Mahkota Safir Ratu Hantu',
        value: 1500,
        isObjective: true,
        x: 0,
        y: 1.4,
        z: 0,
        collected: false,
        modelType: 'chalice',
        color: '#38bdf8',
        sparkleColor: '#60a5fa',
        description: 'Mahkota sakral bertahtakan safir biru bersinar.',
      },
      {
        id: 'haunted_urn',
        name: 'Ancient Pharaoh Urn',
        nameIndo: 'Guci Arwah Firaun',
        value: 1100,
        isObjective: true,
        x: -8,
        y: 1.1,
        z: -4,
        collected: false,
        modelType: 'ancient_urn',
        color: '#f59e0b',
        sparkleColor: '#fde047',
        description: 'Guci tembikar emas berisi asap roh penjaga.',
      },
      {
        id: 'enchanted_dagger',
        name: 'Spectre Dagger',
        nameIndo: 'Belati Bertuah Kuno',
        value: 1250,
        isObjective: true,
        x: 8,
        y: 1.1,
        z: 4,
        collected: false,
        modelType: 'chalice',
        color: '#c084fc',
        sparkleColor: '#e879f9',
        description: 'Belati perak berukir aksara gaib.',
      },
      {
        id: 'skull_obsidian',
        name: 'Obsidian Skull',
        nameIndo: 'Tengkorak Kristal Hitam',
        value: 1300,
        isObjective: true,
        x: 8,
        y: 1.1,
        z: -4,
        collected: false,
        modelType: 'skull',
        color: '#94a3b8',
        sparkleColor: '#f1f5f9',
        description: 'Tengkorak obsidian yang dingin menusuk.',
      },
      // Bonus coins
      {
        id: 'bonus_gem_1',
        name: 'Amethyst Cluster',
        nameIndo: 'Bongkahan Kecubung',
        value: 350,
        isObjective: false,
        x: -8,
        y: 1.1,
        z: 4,
        collected: false,
        modelType: 'gem',
        color: '#a855f7',
        sparkleColor: '#d8b4fe',
        description: 'Permata ungu berkilauan.',
      },
    ],
    ghosts: [
      {
        id: 'ghost_sergeant',
        name: 'Sersan Spook',
        role: 'polisi',
        x: 0,
        y: 1.3,
        z: -5,
        rotationY: 0,
        speed: 2.2,
        chaseSpeed: 3.8,
        state: 'patrol',
        patrolPoints: [
          { x: 0, z: -5, waitTime: 2.0 },
          { x: -8, z: 0, waitTime: 2.5 },
          { x: 0, z: 5, waitTime: 2.0 },
          { x: 8, z: 0, waitTime: 2.5 },
        ],
        currentWaypointIdx: 0,
        targetInvestigatePos: null,
        stateTimer: 0,
        alertLevel: 0,
        visionAngle: Math.PI / 2.6,
        visionDistance: 8.0,
        hearingDistance: 6.5,
        color: '#818cf8', // Indigo spirit
      },
      {
        id: 'ghost_matron',
        name: 'Hantu Penjaga Aula',
        role: 'penjaga',
        x: 7,
        y: 1.3,
        z: 5,
        rotationY: Math.PI,
        speed: 1.6,
        chaseSpeed: 3.2,
        state: 'patrol',
        patrolPoints: [
          { x: 7, z: 5, waitTime: 3.0 },
          { x: 7, z: -5, waitTime: 3.0 },
          { x: 0, z: -2, waitTime: 2.0 },
        ],
        currentWaypointIdx: 0,
        targetInvestigatePos: null,
        stateTimer: 0,
        alertLevel: 0,
        visionAngle: Math.PI / 2.2,
        visionDistance: 7.0,
        hearingDistance: 5.5,
        color: '#f43f5e', // Menacing pinkish-red ghost
      },
    ],
  },

  {
    id: 3,
    title: 'Level 3: Brankas Rahasia Arwah',
    titleIndo: 'Lantai 3: Brankas Rahasia Arwah',
    subtitle: 'Tantangan tertinggi! 3 Hantu berpatroli, kumpulkan 5 harta karun legendaris!',
    theme: 'vault',
    timeLimitSeconds: 260,
    parTimeSeconds: 110,
    playerStart: { x: 0, z: 12, rotationY: Math.PI },
    exitDoor: { x: 0, z: 13.8, width: 2.4, height: 3.2, depth: 0.4 },
    rooms: [
      { x: 0, z: 8, width: 14, depth: 8, name: 'Koridor Depan Brankas', floorTexture: 'stone', wallColor: '#09090b' },
      { x: -7, z: -2, width: 8, depth: 12, name: 'Kamar Relik Barat', floorTexture: 'carpet_red', wallColor: '#1c1917' },
      { x: 7, z: -2, width: 8, depth: 12, name: 'Kamar Relik Timur', floorTexture: 'wood', wallColor: '#1e1b4b' },
      { x: 0, z: -6, width: 6, depth: 8, name: 'Kamar Brankas Pusat', floorTexture: 'checker', wallColor: '#3b0764' },
    ],
    walls: [
      // Outer perimeter
      { x1: -12, z1: -11, x2: 12, z2: -11, thickness: 0.6, height: 3.8 },
      { x1: -12, z1: 14, x2: 12, z2: 14, thickness: 0.6, height: 3.8 },
      { x1: -12, z1: -11, x2: -12, z2: 14, thickness: 0.6, height: 3.8 },
      { x1: 12, z1: -11, x2: 12, z2: 14, thickness: 0.6, height: 3.8 },

      // Front corridor dividing wall
      { x1: -12, z1: 4, x2: -3, z2: 4, thickness: 0.5, height: 3.8 },
      { x1: 3, z1: 4, x2: 12, z2: 4, thickness: 0.5, height: 3.8 },

      // Central vault chamber walls
      { x1: -4, z1: 4, x2: -4, z2: -2, thickness: 0.5, height: 3.8 },
      { x1: 4, z1: 4, x2: 4, z2: -2, thickness: 0.5, height: 3.8 },
      { x1: -4, z1: -2, x2: -2, z2: -2, thickness: 0.5, height: 3.8 },
      { x1: 2, z1: -2, x2: 4, z2: -2, thickness: 0.5, height: 3.8 },
    ],
    furniture: [
      { type: 'pillar', x: 0, y: 0.6, z: -6, width: 2.0, height: 1.2, depth: 2.0, color: '#eab308' },
      { type: 'bookshelf', x: -10.5, y: 1.6, z: -2, width: 0.8, height: 3.2, depth: 4.0, color: '#451a03' },
      { type: 'cabinet', x: 10.5, y: 1.5, z: -2, width: 0.8, height: 3.0, depth: 4.0, color: '#451a03' },
      { type: 'table', x: -7, y: 0.5, z: -2, width: 2.4, height: 1.0, depth: 1.6, color: '#78350f' },
      { type: 'table', x: 7, y: 0.5, z: -2, width: 2.4, height: 1.0, depth: 1.6, color: '#78350f' },
    ],
    hidingSpots: [
      { id: 'wardrobe_vault_1', type: 'wardrobe', x: -8, y: 0, z: 12.5, rotationY: 0, isOpen: false },
      { id: 'wardrobe_vault_2', type: 'wardrobe', x: 8, y: 0, z: 12.5, rotationY: 0, isOpen: false },
      { id: 'wardrobe_vault_3', type: 'wardrobe', x: -10, y: 0, z: -8, rotationY: Math.PI / 2, isOpen: false },
    ],
    loot: [
      {
        id: 'diamond_key',
        name: 'Diamond Vault Key',
        nameIndo: 'Kunci Brankas Intan',
        value: 2000,
        isObjective: true,
        x: 0,
        y: 1.4,
        z: -6,
        collected: false,
        modelType: 'chalice',
        color: '#67e8f9',
        sparkleColor: '#a5f3fc',
        description: 'Kunci berkilau untuk membuka portal harta purba.',
      },
      {
        id: 'ruby_chalice',
        name: 'Blood Chalice',
        nameIndo: 'Cawan Darah Murni',
        value: 1600,
        isObjective: true,
        x: -7,
        y: 1.1,
        z: -2,
        collected: false,
        modelType: 'chalice',
        color: '#dc2626',
        sparkleColor: '#f87171',
        description: 'Cawan permata merah delima bergetar lembut.',
      },
      {
        id: 'spectral_mask',
        name: 'Golden Ghost Mask',
        nameIndo: 'Topeng Emas Raja Hantu',
        value: 1800,
        isObjective: true,
        x: 7,
        y: 1.1,
        z: -2,
        collected: false,
        modelType: 'skull',
        color: '#eab308',
        sparkleColor: '#fef08a',
        description: 'Topeng keramat bertatahkan emas 24 karat.',
      },
      {
        id: 'music_box_gold',
        name: 'Golden Symphony Box',
        nameIndo: 'Kotak Musik Simfoni Arwah',
        value: 1400,
        isObjective: true,
        x: -5,
        y: 0.9,
        z: 8,
        collected: false,
        modelType: 'music_box',
        color: '#f59e0b',
        sparkleColor: '#ec4899',
        description: 'Kotak musik antik dari abad pertengahan.',
      },
      {
        id: 'urn_celestial',
        name: 'Celestial Urn',
        nameIndo: 'Guci Bintang Abadi',
        value: 1500,
        isObjective: true,
        x: 5,
        y: 1.0,
        z: 8,
        collected: false,
        modelType: 'ancient_urn',
        color: '#8b5cf6',
        sparkleColor: '#c084fc',
        description: 'Guci ungu berkilau taburan serbuk bintang.',
      },
    ],
    ghosts: [
      {
        id: 'ghost_chief',
        name: 'Kepala Polisi Hantu',
        role: 'polisi',
        x: 0,
        y: 1.3,
        z: 0,
        rotationY: 0,
        speed: 2.3,
        chaseSpeed: 4.0,
        state: 'patrol',
        patrolPoints: [
          { x: 0, z: 2, waitTime: 2.0 },
          { x: -5, z: 2, waitTime: 2.5 },
          { x: 0, z: -6, waitTime: 2.0 },
          { x: 5, z: 2, waitTime: 2.5 },
        ],
        currentWaypointIdx: 0,
        targetInvestigatePos: null,
        stateTimer: 0,
        alertLevel: 0,
        visionAngle: Math.PI / 2.5,
        visionDistance: 8.5,
        hearingDistance: 7.0,
        color: '#06b6d4',
      },
      {
        id: 'ghost_dog',
        name: 'Anjing Hantu Pelacak',
        role: 'anjing_hantu',
        x: -7,
        y: 0.8,
        z: 0,
        rotationY: 0,
        speed: 2.6,
        chaseSpeed: 4.2,
        state: 'patrol',
        patrolPoints: [
          { x: -7, z: 4, waitTime: 1.5 },
          { x: -7, z: -6, waitTime: 1.5 },
          { x: 0, z: 8, waitTime: 2.0 },
        ],
        currentWaypointIdx: 0,
        targetInvestigatePos: null,
        stateTimer: 0,
        alertLevel: 0,
        visionAngle: Math.PI / 3,
        visionDistance: 6.5,
        hearingDistance: 9.0, // Extra sensitive hearing!
        color: '#10b981',
      },
      {
        id: 'ghost_keeper',
        name: 'Arwah Penjaga Brankas',
        role: 'penjaga',
        x: 7,
        y: 1.3,
        z: 0,
        rotationY: Math.PI,
        speed: 1.8,
        chaseSpeed: 3.4,
        state: 'patrol',
        patrolPoints: [
          { x: 7, z: -6, waitTime: 2.5 },
          { x: 7, z: 4, waitTime: 2.5 },
          { x: 2, z: -4, waitTime: 2.0 },
        ],
        currentWaypointIdx: 0,
        targetInvestigatePos: null,
        stateTimer: 0,
        alertLevel: 0,
        visionAngle: Math.PI / 2.4,
        visionDistance: 7.5,
        hearingDistance: 6.0,
        color: '#ec4899',
      },
    ],
  },
];
